name: admin ci

on:
  push:
    branches:
      - admin

jobs:
  build-and-deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy admin to Server
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.SERVER_HOST_NAME }}
          REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
          TARGET: ${{ secrets.SERVER_WEB_TARGET }}
  