name: web mobile ci

on:
  push:
    branches:
      - mobile

jobs:
  build-and-deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy mobile to Server
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'm/'
          REMOTE_HOST: ${{ secrets.SERVER_HOST_NAME }}
          REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
          TARGET: ${{ secrets.SERVER_M_TARGET }}

      - name: ssh-agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        env:
          SERVER_HOST_NAME: ${{ secrets.SERVER_HOST_NAME }}

      - name: Setup knownhosts
        run: ssh-keyscan ${{ secrets.SERVER_HOST_NAME }} >> ~/.ssh/known_hosts

      - name: Run SSH Command To build mobile server
        run: ssh root@${{ secrets.SERVER_HOST_NAME }} "(docker stop wentao-m || true) && (docker rm wentao-m || true) && (docker rmi wentao-m || true) && cd /fay/service/wentao/m/ && docker build -t wentao-m . && docker run --restart=always -d -p 3004:3000 --name wentao-m wentao-m"
      

  