name: web pc ci

on:
  push:
    branches:
      - pc

jobs:
  build-and-deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy pc to Server
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'pc/'
          REMOTE_HOST: ${{ secrets.SERVER_HOST_NAME }}
          REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
          TARGET: ${{ secrets.SERVER_PC_TARGET }}

      - name: ssh-agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        env:
          SERVER_HOST_NAME: ${{ secrets.SERVER_HOST_NAME }}

      - name: Setup knownhosts
        run: ssh-keyscan ${{ secrets.SERVER_HOST_NAME }} >> ~/.ssh/known_hosts

      - name: Run SSH Command To build pc server
        run: ssh root@${{ secrets.SERVER_HOST_NAME }} "(docker stop wentao-pc || true) && (docker rm wentao-pc || true) && (docker rmi wentao-pc || true) && cd /fay/service/wentao/pc/ && docker build -t wentao-pc . && docker run --restart=always -d -p 3005:3000 --name wentao-pc wentao-pc"
      

  